### ISSUE TITLE
Viewer not rendering

### ISSUE THREAD

**Issue by mshooter** [JeromeEippers/AnimationTech#1]
Hi Jerôme, 

I really appreciate you releasing the code. 
I had an enquiry, I am trying to run the notebooks however, I am not able to see the renders after "viewer" is executed. 
It is just a blank screen. 

Is there something else I need to do? 
I have installed all the packages from the requirements.txt file. 
I am on a MacOS (M2).

Thank you. 
<img width="1228" alt="Screenshot 2024-06-14 at 12 39 11" src="https://github.com/JeromeEippers/AnimationTech/assets/23126918/bc1b73ba-20c2-4cec-9653-ac47cd575b86">

**Comment by JeromeEippers** [comment]
Hi Moira,

That is sad :(
I have it working on windows and on ubuntu and unfortunately my old Mac is so old and it is still on a safari that does not support webgl2.

stupid question, but is this working  https://get.webgl.org/webgl2/ ?

Cheers,
jerome

**Comment by mshooter** [comment]
Hi Jerome, 

Yes indeed, I was excited to go through your notebooks!
The link you sent me does work :) 
I am wondering if it is link with the ipywidgets with M2 chips.. 

Cheers,
Moira

**Comment by JeromeEippers** [comment]
Hi Moira,

1. Do you have any warning in your developer log?
2. Does libraries like ipycanvas works?

Cheers, 
Jerome

**Comment by JeromeEippers** [comment]
Hi Moira,

I've been able to test on my old Mac.
The issue is with the shadows. 
If you draw nothing between the begin_shadow() and end_shadow() you should have something that renders.

I'll try to see if I can fix this

**Comment by mshooter** [comment]
Hi Jerome, 

thank you so much it works now ! 
Looking forward to play around with your notebooks & hopefully you will be able to fix this :D
